job_name: nemo_gpt
nodes: 1
tasks_per_node: 1
gpus_per_node: 1
container: $HOME/containers/cuda_uv_12.sif
train_script: /opt/NeMo/examples/nlp/language_modeling/megatron_gpt_pretraining.py
config_path: /opt/NeMo/examples/nlp/language_modeling/conf
config_name: megatron_gpt_config.yaml
data_mount: /data
output_mount: /output
modules:
  - cuda/12.1
  - python-uv
overrides:
  - trainer.devices=4
  - trainer.num_nodes=2
  - trainer.strategy=ddp
  - exp_manager.exp_dir=/mnt/output/exp
  - model.train_ds.file_path=/mnt/data/my_data.json
